name: Run Python Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * *"  # Runs every day at 6 AM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install compatible numpy to avoid np.float_ error
          python -m pip install "numpy<2.0"
          # Install Prophet
          python -m pip install --upgrade prophet
          # Install remaining requirements
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure Git for GitHub access
        run: git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Run Crypto Forecast Script
        run: python crypto_forecasting.py
