name: Run Python Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * *"  # Run every day at 6 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Configure GitHub access (optional, if needed)
      - name: Configure Git for GitHub access
        run: git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      # Step 4: Install dependencies safely
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Pin NumPy <2.0 to avoid Prophet np.float_ issue
          pip install "numpy<2.0"
          # Install remaining dependencies from requirements
          pip install -r requirements.txt

      # Step 5: Run your script
      - name: Run Crypto Forecast Script
        run: python crypto_forecasting.py
